{
  config,
  pkgs,
  lib,
  workSystem ? false,
  ...
}:

let
  sshData = import ../../../../resources/ssh/hosts.nix;
  defaultsCommon = sshData.defaults.common;
  defaultsProfile = if workSystem then sshData.defaults.dacoso else sshData.defaults.personal;
  hostsProfile = if workSystem then sshData.dacosoHosts else sshData.personalHosts;

  keyFromName = host: if lib.hasAttr "keyName" host then "~/.ssh/personal/${host.keyName}" else null;

  identityFor =
    host:
    let
      namedKey = keyFromName host;
    in
    if lib.hasAttr "identityFile" host then
      host.identityFile
    else if namedKey != null then
      namedKey
    else
      defaultsProfile.defaultIdentity;

  renderExtraOptions =
    extra: lib.concatStringsSep "" (lib.mapAttrsToList (k: v: "  ${k} ${toString v}\n") extra);

  renderHost =
    host:
    ''
      Host ${host.match or host.alias}
        HostName ${host.hostName or host.alias}
        User ${host.user or defaultsProfile.user}
        Port ${toString (host.port or defaultsCommon.port)}
        IdentitiesOnly yes
        IdentityFile ${identityFor host}
        ControlMaster auto
        ControlPersist ${host.controlPersist or defaultsCommon.controlPersist}
    ''
    + (renderExtraOptions (host.extraOptions or { }))
    + "\n";

  renderHostsFile =
    label: hosts:
    ''
      # Generated by Home Manager from resources/ssh/hosts/${label}.nix
      # workSystem: ${if workSystem then "true" else "false"}

    ''
    + lib.concatStringsSep "" (map renderHost hosts);
in
{
  imports = [
    ./sshpass.nix
  ];

  # Fix key directory permissions on activation so ssh-agent and ssh honor keys
  home.activation.fixSshPerms = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    chmod 700 "${config.home.homeDirectory}/.ssh"
    find "${config.home.homeDirectory}/.ssh" -type d -exec chmod 700 {} +
    find "${config.home.homeDirectory}/.ssh" -type f -exec chmod 600 {} +
  '';

  programs.ssh = {
    enable = true;
    enableDefaultConfig = false;

    extraConfig = ''
      SetEnv TERM=xterm
      ServerAliveInterval 30
      ServerAliveCountMax 3
      VisualHostKey no
      HashKnownHosts yes
      IdentitiesOnly yes
      Include ~/.ssh/config.d/*
    '';

    matchBlocks."*" = { };
  };

  home.file.".ssh/config.d/10-git".text =
    if workSystem then
      ''
        # Work Git identities
        Host github.com
          HostName github.com
          User git
          IdentitiesOnly yes
          IdentityFile ~/.ssh/id_ed25519_dacoso

        Host bitbucket.org
          HostName bitbucket.org
          User git
          IdentitiesOnly yes
          IdentityFile ~/.ssh/bitbucket
      ''
    else
      ''
        # Personal Git identities
        Host github.com
          HostName github.com
          User git
          IdentitiesOnly yes
          IdentityFile ~/.ssh/personal/id_ed25519

        Host github-dacoso
          HostName github.com
          User git
          IdentitiesOnly yes
          IdentityFile ~/.ssh/id_ed25519_dacoso
      '';

  home.file.".ssh/config.d/20-hosts".text = renderHostsFile (
    if workSystem then "dacoso" else "personal"
  ) hostsProfile;

  home.file.".ssh/config.d/40-chaospott" = lib.mkIf (!workSystem && !pkgs.stdenv.isDarwin) {
    source = ../../../../resources/ssh/config.d/chaospott;
  };
}
