#!/usr/bin/env bash
# Generate and encrypt a per-host SSH management keypair.

set -euo pipefail

if [[ $# -lt 2 ]]; then
  cat <<'USAGE'
Usage: scripts/servers/create-management-key.sh <host> <scope>

Scopes:
  personal   -> installs keys for ~/.ssh on tux + tab and writes public key for the host
  work/dacoso -> installs keys for the Macbook Pro secret tree

Example:
  scripts/servers/create-management-key.sh docker-host-01 dacoso
USAGE
  exit 1
fi

host="$1"
scope="$2"
repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

timestamp="$(date -u +%Y%m%dT%H%M%SZ)"
key_label="${host}-${scope}-mgmt"
tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

echo ">> Generating dedicated SSH key for ${host} (${scope})"
ssh-keygen -t ed25519 -C "${host} mgmt ${timestamp}" -f "${tmpdir}/id_ed25519" -N "" >/dev/null

declare -a manager_paths
identity_hint="personal"
case "${scope}" in
  personal)
    manager_paths=(
      "secrets/profiles/personal/desktops/common/ssh"
    )
    identity_hint="personal"
    host_scope_dir="secrets/profiles/personal/servers/${host}/ssh"
    ;;
  dacoso|work)
    manager_paths=(
      "secrets/profiles/work/desktops/macbook-pro/ssh"
    )
    identity_hint="work"
    host_scope_dir="secrets/profiles/work/servers/${host}/ssh"
    ;;
  *)
    echo "!! Unknown scope '${scope}'. Use 'personal' or 'work' (alias 'dacoso')." >&2
    exit 2
    ;;
esac

for dir in "${manager_paths[@]}"; do
  mkdir -p "${dir}"
  dest_priv="${dir}/${key_label}.priv"
  echo ">> Storing encrypted private key at ${dest_priv}"
  if command -v sops >/dev/null 2>&1; then
    # Encrypt in place so creation rules match the destination path
    cp "${tmpdir}/id_ed25519" "${dest_priv}"
    SOPS_CONFIG="${repo_root}/.sops.yaml" \
      sops --verbose --encrypt --input-type binary --in-place "${dest_priv}"
  else
    echo "!! sops not found – writing unencrypted private key. Run 'nix run nixpkgs#sops -- --encrypt ${dest_priv}' later!" >&2
    cp "${tmpdir}/id_ed25519" "${dest_priv}"
  fi
done

mkdir -p "${host_scope_dir}"
dest_host_pub="${host_scope_dir}/${key_label}.pub"
cp "${tmpdir}/id_ed25519.pub" "${dest_host_pub}"
SOPS_CONFIG="${repo_root}/.sops.yaml" \
  sops --verbose --encrypt --input-type binary --in-place "${dest_host_pub}"
for dir in "${manager_paths[@]}"; do
  dest_pub="${dir}/${key_label}.pub"
  echo ">> Storing encrypted public key at ${dest_pub}"
  cp "${tmpdir}/id_ed25519.pub" "${dest_pub}"
  SOPS_CONFIG="${repo_root}/.sops.yaml" \
    sops --verbose --encrypt --input-type binary --in-place "${dest_pub}"
done
echo ">> Saved encrypted public key to ${dest_host_pub} and manager paths"

cat <<EOF

Next steps for ${host}:
  1. Commit the new key material in secrets (they are encrypted according to .sops.yaml).
  2. Add the following entry to resources/ssh/hosts/personal.nix if it does not exist yet:

     {
       alias = "${host}";
       hostName = "${host}";
       match = "${host}";
       user = "root";
       identity = "${identity_hint}";
       description = "Autogenerated on ${timestamp}";
     }

  3. Decrypt the key on the managing workstation with:
       sops -d ${manager_paths[0]}/${key_label}.priv > ~/.ssh/${key_label}
     and set correct permissions (chmod 600).
  4. Push the public key into the remote host's /root/.ssh/authorized_keys during bootstrap.

EOF
