#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 2 ]]; then
  cat <<'USAGE'
Usage: scripts/servers/create-management-key.sh <host> <scope>

Scopes:
  personal   -> installs keys for ~/.ssh on tux + tab and writes public key for the host
  dacoso     -> installs keys for the Macbook Pro secret tree

Example:
  scripts/servers/create-management-key.sh docker-host-01 dacoso
USAGE
  exit 1
fi

host="$1"
scope="$2"
timestamp="$(date -u +%Y%m%dT%H%M%SZ)"
key_label="${host}-${scope}-mgmt"
tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

echo ">> Generating dedicated SSH key for ${host} (${scope})"
ssh-keygen -t ed25519 -C "${host} mgmt ${timestamp}" -f "${tmpdir}/id_ed25519" -N "" >/dev/null

declare -a manager_paths
identity_hint="personal"
case "${scope}" in
  personal)
    manager_paths=(
      "secrets/personal/tux-h4xx-01/ssh"
      "secrets/personal/tab-h4xx-02/ssh"
    )
    identity_hint="personal"
    ;;
  dacoso)
    manager_paths=(
      "secrets/dacoso/Macbook-Pro.local/ssh"
    )
    identity_hint="work"
    ;;
  *)
    echo "!! Unknown scope '${scope}'. Use 'personal' or 'dacoso'." >&2
    exit 2
    ;;
esac

for dir in "${manager_paths[@]}"; do
  mkdir -p "${dir}"
  dest_priv="${dir}/${key_label}.priv"
  echo ">> Storing encrypted private key at ${dest_priv}"
  if command -v sops >/dev/null 2>&1; then
    sops --encrypt --input-type binary --output "${dest_priv}" "${tmpdir}/id_ed25519"
  else
    echo "!! sops not found – writing unencrypted private key. Run 'nix run nixpkgs#sops -- --encrypt ${dest_priv}' later!" >&2
    cp "${tmpdir}/id_ed25519" "${dest_priv}"
  fi
done

host_secret_dir="secrets/hosts/${host}/ssh"
mkdir -p "${host_secret_dir}"
cp "${tmpdir}/id_ed25519.pub" "${host_secret_dir}/${key_label}.pub"
echo ">> Saved public key to ${host_secret_dir}/${key_label}.pub"

cat <<EOF

Next steps for ${host}:
  1. Commit the new key material in secrets (they are encrypted according to .sops.yaml).
  2. Add the following entry to resources/ssh/hosts.nix if it does not exist yet:

     {
       alias = "${host}";
       hostName = "${host}";
       match = "${host}";
       user = "root";
       identity = "${identity_hint}";
       description = "Autogenerated on ${timestamp}";
     }

  3. Decrypt the key on the managing workstation with:
       sops -d ${manager_paths[0]}/${key_label}.priv > ~/.ssh/${key_label}
     and set correct permissions (chmod 600).
  4. Push the public key into the remote host's /root/.ssh/authorized_keys during bootstrap.

EOF
